import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { Toaster } from "react-hot-toast";

import { CartProvider } from '@/context/CartContext';
import { LanguageProvider } from '@/context/LanguageContext';
import { OrderProvider } from '@/context/OrderContext';
import Footer from '@/components/layout/Footer';
import FooterWrapper from "./FooterWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Sử dụng NEXT_PUBLIC_ prefix để có thể truy cập từ client-side
const clientId = process.env.GOOGLE_CLIENT_ID;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (!clientId) {
    console.warn('Google Client ID is not configured. Google Sign-In will not work.');
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider>
          <CartProvider>
            <OrderProvider>
              <GoogleOAuthProvider clientId={clientId || ''}>
                {children}
                <FooterWrapper />
                <Toaster />
              </GoogleOAuthProvider>
            </OrderProvider>
          </CartProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
